Filament v3 support
stechstudio/filament-impersonate pull request #32
Opened 2023-02-17 09:05 UTC by pxlrbt

> :Warning: 
> This is a breaking change, as Filament v3 registers plugins differently.

This PR adds support for Filament v3.

2023-05-12 12:35 UTC, pxlrbt commented
Just updated this, since the first PR had issues across guards as it still used a config option that isn't available anymore.

2023-07-23 19:10 UTC, Saifallak commented
Could not check compatibility between STS\FilamentImpersonate\FilamentImpersonatePlugin::register(Filament\Context $context): void and Filament\Contracts\Plugin::register(Filament\Panel $panel): void, because class Filament\Context is not available

2023-07-23 19:14 UTC, Saifallak commented on src/FilamentImpersonatePlugin.php
> +}
```suggestion
<?php

namespace STS\FilamentImpersonate;

use Filament\Panel;
use Filament\Contracts\Plugin;
use STS\FilamentImpersonate\Middleware\ImpersonationBanner;

class FilamentImpersonatePlugin implements Plugin
{
    public function getId(): string
    {
        return 'filament-impersonate';
    }

    public function register(Panel $panel): void
    {
        $panel->middleware([
            ImpersonationBanner::class
        ]);
    }

    public function boot(Panel $panel): void
    {
        //
    }
}
```

2023-07-23 19:23 UTC, Saifallak requested changes

2023-07-23 19:23 UTC, Saifallak commented on src/Impersonate.php
>  }
```suggestion
<?php

namespace STS\FilamentImpersonate;

use Closure;
use Filament\Facades\Filament;
use Filament\Tables\Actions\Action;
use Illuminate\Http\RedirectResponse;
use Lab404\Impersonate\Services\ImpersonateManager;
use Livewire\Redirector;

class Impersonate extends Action
{
    protected Closure|string|null $guard = null;

    protected Closure|string|null $redirectTo = null;

    public static function getDefaultName(): ?string
    {
        return 'impersonate';
    }

    protected function setUp(): void
    {
        parent::setUp();

        $this
            ->iconButton()
            ->icon('impersonate-icon')
            ->action(fn ($record) => $this->impersonate($record))
            ->hidden(fn ($record) => !static::allowed(Filament::auth()->user(), $record));
    }

    public function guard(Closure|string $guard): self
    {
        $this->guard = $guard;

        return $this;
    }

    public function redirectTo(Closure|string $redirectTo): self
    {
        $this->redirectTo = $redirectTo;

        return $this;
    }

    public function getGuard(): string
    {
        return $this->evaluate($this->guard) ?? config('filament-impersonate.guard');
    }

    public function getRedirectTo(): string
    {
        return $this->evaluate($this->redirectTo) ?? config('filament-impersonate.redirect_to');
    }

    protected static function allowed($current, $target): bool
    {
        return $current->isNot($target)
            && !app(ImpersonateManager::class)->isImpersonating()
            && (!method_exists($current, 'canImpersonate') || $current->canImpersonate())
            && (!method_exists($target, 'canBeImpersonated') || $target->canBeImpersonated());
    }

    public function impersonate($record): bool|Redirector|RedirectResponse|\Livewire\Features\SupportRedirects\Redirector
    {
        if (!static::allowed(Filament::auth()->user(), $record)) {
            return false;
        }

        app(ImpersonateManager::class)->take(
            Filament::auth()->user(),
            $record,
            $this->getGuard()
        );

        session()->forget(array_unique([
            'password_hash_' . config('filament-impersonate.guard'),
            'password_hash_' . Filament::getCurrentPanel()->getAuthGuard()
        ]));
        session()->put('impersonate.back_to', request('fingerprint.path'));
        session()->put('impersonate.back_to_panel', Filament::getCurrentPanel()->getId());

        return redirect($this->getRedirectTo());
    }

    public static function leave(): bool|Redirector|RedirectResponse|\Livewire\Features\SupportRedirects\Redirector
    {
        if(!app(ImpersonateManager::class)->isImpersonating()) {
            return redirect('/');
        }

        app(ImpersonateManager::class)->leave();

        $panel = Filament::getPanel(session()->get('impersonate.back_to_panel'));

        session()->forget(array_unique([
            'password_hash_' . config('filament-impersonate.guard'),
            'password_hash_' . Filament::getCurrentPanel()->getAuthGuard(),
            'password_hash_' . $panel->getAuthGuard(),
        ]));

        return redirect(
            session()->pull('impersonate.back_to') ?? $panel->getUrl()
        );
    }
}

```

2023-07-23 19:24 UTC, Saifallak commented
but after all those edits still getting
```
Filament\FilamentManager::getUserName(): Argument #1 ($user) must be of type Illuminate\Database\Eloquent\Model|Illuminate\Contracts\Auth\Authenticatable, null given, called in ....\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 353


```

2023-07-24 07:24 UTC, pxlrbt commented
I'll have another look at this. This was working with an earlier alpha version.

2023-07-24 10:03 UTC, Saifallak commented
i managed to get it fixed, in #42, and made a PR for you too,

can you review it?

2023-07-24 12:22 UTC, pxlrbt commented
Thanks @Saifallak. Looked good and I merged them into my PR.

2023-07-24 13:11 UTC, Saifallak commented
@pxlrbt I know it's a headache, but can you rebase with the current master? so the owner (@stechstudio) can merge it.

2023-07-24 13:49 UTC, jszobody commented
This is amazing, thanks so much folks. I haven't had a chance to fire up v3 yet, though I'm eager to! If you both say this PR is working well in v3, I'm happy to merge it and tag a release once conflicts are resolved.

2023-07-27 07:32 UTC, pxlrbt commented
I just merged the current master branch into this PR. There were a lot of changes since the time I started the PR so please have another look at it @jszobody.

I tested this with Filament Demo and a single Panel. @Saifallak Do you have an app with multiple panels that use different auth guards where you can test this, too? Mine is still stuck on alpha.

2023-07-27 12:45 UTC, Saifallak commented
@pxlrbt thanks for your hard work.

Currently i dont have any app eith multiple panels,
But planning to work on one in next days.
And I'll try it.

For now, i tested it in single panel and works well (except for banner issue you mentioned)

2023-07-27 15:30 UTC, jszobody commented
@pxlrbt Wonderful, I'll merge and tag a v3 release. Any documentation updates needed in the README file first?

2023-07-27 15:32 UTC, pxlrbt commented
I don't think so. I removed the plugin again, because I think Impersonate is something that should be enabled globally and not per Panel. So everything is still registered via the ServiceProvider.

2023-07-27 15:32 UTC, merged

2023-07-27 15:35 UTC, jszobody commented
Version `3.0` is released! Thanks everyone.